Add files via upload
OlyaKorolko/MatrixCalc pull request #1
Opened 2020-09-15 19:29 UTC by OlyaKorolko

2020-09-15 20:15 UTC, VeronikaYastr requested changes

2020-09-15 20:15 UTC, VeronikaYastr commented on src/main/com/company/Main.java
> +        System.out.println("Your randomly generated matrix: ");
Лучше вывод матрицы вынести в отдельный метод и его вызывать уже в main() после генерации

Либо просто перенести этот код в main(). Метод generateRandMatrix() должен просто генерировать матрицу и возвращать ее. Остальные действия лишние

Кстати, зачем передавать в него матрицу и размеры?

Лучше передавать только rows, cols, в самом методе создавать матрицу и возвращать ее. А в мэйне присваивать результат какой-то новой переменной

2020-09-15 20:15 UTC, VeronikaYastr commented on src/main/com/company/Main.java
> +        System.out.println();
Зачем здесь вывод пустой строки?)

2020-09-15 20:15 UTC, VeronikaYastr commented on src/main/com/company/Main.java
> +    public static ArrayList<Integer> getRightCols(int[][] matrix, int cols) {
Зачем передавать размер матрицы параметром cols, если можно просто взять matrix.length или matrix[0].length?

2020-09-15 20:15 UTC, VeronikaYastr commented on src/main/com/company/Main.java
> +        for (int k = 0; k < cols; ++k) {
Имеет ли смысл проходиться по матрице два раза, сначала помечая нужные столбцы, а потом еще раз, добавляя их в список?

2020-09-15 20:15 UTC, VeronikaYastr commented on src/test/com/company/MainTest.java
> +    void TestMatrix() {
`testMatrix` (camelCase)

Лучше разбить на 2-3 теста с одной проверкой в каждом

Нет смысла проверять одинаковые случаи с разным размером. Можно например сделать, testIncreasingSequence, testDecreasingSequence, testIncreasingAndDecreasingSequence...

То есть чтобы когда тесты прошли, было по названиям видно, какие случаи тестировались. Ну и соответственно если что-то упадет, будет сразу видно, в чем был смысл

2020-09-15 20:50 UTC, OlyaKorolko commented on src/test/com/company/MainTest.java
> +    void TestMatrix() {
А для каждого теста нужно делать новый класс или новую функцию в классе?

2020-09-15 20:54 UTC, VeronikaYastr commented on src/test/com/company/MainTest.java
> +    void TestMatrix() {
Функции, помеченные аннотацией @Test🙂

2020-09-15 20:58 UTC, OlyaKorolko commented on src/test/com/company/MainTest.java
> +    void TestMatrix() {
Спасибо)

2020-09-16 20:18 UTC, VeronikaYastr commented
Можно мержить, все хорошо)

2020-09-16 21:07 UTC, merged